spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyServiceDB
    username: admin
    password: password

core:
  clients:
    pension-age-threshold:
      maleAgeThreshold: 63
      femaleAgeThreshold: 58

spring.security.user.name: admin
spring.security.user.password: password