package ru.medicaltickets.MyServiceJava.doctor.enums;

public enum DoctorsSpecialties {
    CARDIOVASCULAR_SURGEON,
    ELECTROPHYSIOLOGIST,
    ENT_SPECIALIST,
    ENT_SURGEON,
    FAMILY_PHYSICIAN,
    GENERAL_PRACTITIONER,
    GYNECOLOGICAL_ENDOCRINOLOGIST,
    GYNECOLOGIST,
    NEONATOLOGIST,
    OBSTETRICIAN_GYNECOLOGIST,
    OPHTHALMIC_SURGEON,
    OPHTHALMOLOGIST,
    PEDIATRIC_ENDOCRINOLOGIST,
    PEDIATRIC_OPHTHALMOLOGIST,
    PEDIATRICIAN
}
